version: '2'

services:
  # ############ Performance monitoring ###########################################
  influxsrv:
      image: tutum/influxdb #:0.9.6.1
      container_name: influxsrv
      volumes:
        - ./.data/influxdb:/data
      ports:
        - "8083:8083"
        - "8086:8086"
      expose:
        - "8090"
        - "8099"
      environment:
        - PRE_CREATE_DB=cadvisor
  cadvisor:
      image: google/cadvisor
      container_name: cadvisor
      command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      links:
        - influxsrv:influxsrv
      depends_on:
        - influxsrv
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      links:
        - influxsrv:influxsrv
      depends_on:
        - influxsrv
      environment:
        - HTTP_USER=admin
        - HTTP_PASS=admin
        - INFLUXDB_HOST=influxsrv
        - INFLUXDB_PORT=8086
        - INFLUXDB_NAME=cadvisor
        - INFLUXDB_USER=root
        - INFLUXDB_PASS=root
